name: xai_v1

dependencies:
  - python=3.7.10
  - numpy=1.20.2
  - scikit-learn=0.24.2
  - matplotlib=3.4.2
  - jupyterlab=3.0.16
  - netcdf4=1.5.7
  - xarray=0.18.2
  - geopandas=0.9.0 
  - rioxarray=0.4.3
  - seaborn=0.11.1
  - numpy-indexed=0.3.5
  - shap=0.39.0
  - pip
  - pip:
    - corels
    - lime==0.2.0.1

  

